---
title: "R Evaluation"
date: "06/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Time: 3 hours
#### Max marks:100

## [Kickstarter Projects](https://www.kaggle.com/kemical/kickstarter-projects?select=ks-projects-201612.csv)
### More than 300,000 kickstarter projects

Download the data from:

https://rawgit.com/Parvathy47/R-Programming/master/Exam/Q11.csv

**Context**

I'm a crowdfunding enthusiast and i'm watching kickstarter since its early days. Right now I just collect data and the only app i've made is this twitter bot which tweet any project reaching some milestone: @bloomwatcher . I have a lot of other ideas, but sadly not enough time to develop them… But I hope you can!


**Content**
You'll find most useful data for project analysis. Columns are self explanatory except:

* usd_pledged: conversion in US dollars of the pledged column (conversion done by kickstarter).
* usd pledge real: conversion in US dollars of the pledged column (conversion from Fixer.io API).
* usd goal real: conversion in US dollars of the goal column (conversion from Fixer.io API).

## Questions
***Create an R Shiny App that contains the following features:***

1.The app should have 2 tabs: Home and EDA. **[5]**

2.In the home tab, you need to have 3 options: A general description of the data (available at the start of this file), sorting data and  main_category wise summarizations.**[5]**

3.In the sorting data option, the user can input values as 'top/bottom' using a radio button, usd pledged values using a slider and state (include 'All') using a drop down. Based on the user input you will sort the data and display as a plain table.**[30]**

4.In usd pledged wise summarizations, include a menu to select the usd pledged. Based on the usd pledged selected you have to display the min, max and mean values for the numeric columns selected and mode values for the state column. The columns are displayed as check box values.**[30]**

5.In the EDA option, plot a boxplot for each currency's pledged column, a bar chart showing usd pledged and usd pledged real for each main category and a histogram of country column.**[30]**
