---
title: "R Evaluation"
date: "06/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Time: 3 hours
#### Max marks:100

## [New York City Airbnb Open Data](https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data)
### Daily statistics for trending YouTube videos

Download the data from:

https://rawgit.com/Parvathy47/R-Programming/master/Exam/Q4.csv

**Context**

Since 2008, guests and hosts have used Airbnb to expand on traveling possibilities and present more unique, personalized way of experiencing the world. This dataset describes the listing activity and metrics in NYC, NY for 2019.


**Content**

This data file includes all needed information to find out more about hosts, geographical availability, necessary metrics to make predictions and draw conclusions.

## Questions
***Create an R Shiny App that contains the following features:***

1.The app should have 2 tabs: Home and EDA. **[5]**

2.In the home tab, you need to have 3 options: A general description of the data (available at the start of this file), sorting data and  'room type' wise summarizations.**[5]**

3.In the sorting data option, the user can input values as 'top/bottom' using a radio button, price values using a slider and a neighbourhood group (include 'All') using a drop down. Based on the user input you will sort the data and display as a plain table.**[30]**

4.In room type wise summarizations, include a menu to select the room type. Based on the room type selected you have to display the mean values for the numeric columns selected and mode values for the neighbourhood and host_name. The columns are displayed as check box values.**[30]**

5.In the EDA option, plot a geoplot with color gradient based on the mean price, a boxplot for each room type's review's per month and a histogram of minimum number of nights.**[30]**
