---
title: "R Evaluation"
date: "06/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Time: 3 hours
#### Max marks:100

## [Video Game Sales](https://www.kaggle.com/gregorut/videogamesales)
### Analyze sales data from more than 16,500 games.

Download the data from:

https://rawgit.com/Parvathy47/R-Programming/master/Exam/Q6.csv

**Context**

This dataset contains a list of video games with sales greater than 100,000 copies. It was generated by a scrape of vgchartz.com.


**Content**

* Fields include
* Rank - Ranking of overall sales
* Name - The games name
* Platform - Platform of the games release (i.e. PC,PS4, etc.)
* Year - Year of the game's release
* Genre - Genre of the game
* Publisher - Publisher of the game
* NA_Sales - Sales in North America (in millions)
* EU_Sales - Sales in Europe (in millions)
* JP_Sales - Sales in Japan (in millions)
* Other_Sales - Sales in the rest of the world (in millions)
* Global_Sales - Total worldwide sales.

## Questions
***Create an R Shiny App that contains the following features:***

1.The app should have 2 tabs: Home and EDA. **[5]**

2.In the home tab, you need to have 3 options: A general description of the data (available at the start of this file), sorting data and  platform wise summarizations.**[5]**

3.In the sorting data option, the user can input values as 'top/bottom' using a radio button, rank values using a slider and a genre (include 'All') using a drop down. Based on the user input you will sort the data and display as a plain table.**[30]**

4.In platform wise summarizations, include a menu to select the platform. Based on the platform selected you have to display the min, max and mean values for the numeric columns selected and mode values for the year and publisher. The columns are displayed as check box values.**[30]**

5.In the EDA option, plot a boxplot for each year's global sales, a bar chart showing mean NA, EU and JP sales for each platform and a histogram of genre.**[30]**
