---
title: "R Evaluation"
date: "06/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Time: 3 hours
#### Max marks:100

## [Goodreads-books](https://www.kaggle.com/jealousleopard/goodreadsbooks)
### comprehensive list of all books listed in goodreads

Download the data from:

https://rawgit.com/Parvathy47/R-Programming/master/Exam/Q8.csv

**Context**

The primary reason for creating this dataset is the requirement of a good clean dataset of books. Being a bookie myself (see what I did there?) I had searched for datasets on books in kaggle itself - and I found out that while most of the datasets had a good amount of books listed, there were either a) major columns missing or b) grossly unclean data. I mean, you can't determine how good a book is just from a few text reviews, come on! What I needed were numbers, solid integers and floats that say how many people liked the book or hated it, how much did they like it, and stuff like that. Even the good dataset that I found was well-cleaned, it had a number of interlinked files, which increased the hassle. This prompted me to use the Goodreads API to get a well-cleaned dataset, with the promising features only ( minus the redundant ones ), and the result is the dataset you're at now.



## Questions
***Create an R Shiny App that contains the following features:***

1.The app should have 2 tabs: Home and EDA. **[5]**

2.In the home tab, you need to have 3 options: A general description of the data (available at the start of this file), sorting data and  publisher wise summarizations.**[5]**

3.In the sorting data option, the user can input values as 'top/bottom' using a radio button, average rating values using a slider and publisher (include 'All') using a drop down. Based on the user input you will sort the data and display as a plain table.**[30]**

4.In publisher wise summarizations, include a menu to select the publisher. Based on the publisher selected you have to display the min, max and mean values for the numeric columns selected and mode values for the language	and authors. The columns are displayed as check box values.**[30]**

5.In the EDA option, plot a boxplot for each language's rating's count, a bar chart showing mean   num_pages	ratings_count	text_reviews_count for each author whose books have a rating of at least 4.5  and a histogram of each publisher.**[30]**
