---
title: "R Evaluation"
date: "06/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Time: 3 hours
#### Max marks:100

## [International football results from 1872 to 2020](https://www.kaggle.com/martj42/international-football-results-from-1872-to-2017)
### An up-to-date dataset of over 40,000 international football results

Download the data from:

https://rawgit.com/Parvathy47/R-Programming/master/Exam/Q9.csv

**Context**

Well, what happened was that I was looking for a semi-definite easy-to-read list of international football matches and couldn't find anything decent. So I took it upon myself to collect it for my own use. I might as well share it.

**Content**
This dataset includes 41,586 results of international football matches starting from the very first official match in 1972 up to 2019. The matches range from FIFA World Cup to FIFI Wild Cup to regular friendly matches. The matches are strictly men's full internationals and the data does not include Olympic Games or matches where at least one of the teams was the nation's B-team, U-23 or a league select team.

It includes the following columns:

* date - date of the match
* home_team - the name of the home team
* away_team - the name of the away team
* home_score - full-time home team score including extra time, not including penalty-shootouts
* away_score - full-time away team score including extra time, not including penalty-shootouts
* tournament - the name of the tournament
* city - the name of the city/town/administrative unit where the match was played
* country - the name of the country where the match was played
* neutral - TRUE/FALSE column indicating whether the match was played at a neutral venue

Note on team and country names:
For home and away teams the current name of the team has been used. For example, when in 1882 a team who called themselves Ireland played against England, in this dataset, it is called Northern Ireland because the current team of Northern Ireland is the successor of the 1882 Ireland team. This is done so it is easier to track the history and statistics of teams.

For country names, the name of the country at the time of the match is used. So when Ghana played in Accra, Gold Coast in the 1950s, even though the names of the home team and the country don't match, it was a home match for Ghana. This is indicated by the neutral column, which says FALSE for those matches, meaning it was not at a neutral venue.

## Questions
***Create an R Shiny App that contains the following features:***

1.The app should have 2 tabs: Home and EDA. **[5]**

2.In the home tab, you need to have 3 options: A general description of the data (available at the start of this file), sorting data and  tournament wise summarizations.**[5]**

3.In the sorting data option, the user can input values as 'top/bottom' using a radio button, home_score values using a slider and home_team (include 'All') using a drop down. Based on the user input you will sort the data and display as a plain table.**[30]**

4.In tournament wise summarizations, include a menu to select the tournament. Based on the tournament selected you have to display the min, max and mean values for the numeric columns selected and mode values for the city and country. The columns are displayed as check box values.**[30]**

5.In the EDA option, plot a boxplot for each tournament's away_score, a bar chart showing mean   home_score and away_acore for each country and a histogram of neutral column.**[30]**
